spring:
  application:
    name: HotelService
  datasource:
    url: jdbc:postgresql://localhost:5432/mic_hotel_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format: true
      dialect : org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081











